import { ToastContainer } from "react-toastify";
import "./globals.css";
import GlobalProvider from "@/components/application/GlobalProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-[M_PLUS_Rounded]`}
        suppressHydrationWarning={true}
      >
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}